export const mockRunningAuctionsResponse = [
    {
        uuid: "e01899e3-b683-44a8-8ebb-8db99832e068",
        state: 2,
        endingTime: "2021-09-22T11:26:48.069Z",
        remainingTimeInSeconds: 511396,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 573,
        currentHighestBidValueNet: 573,
        minimumRequiredAsk: 8258,
        minimumRequiredAskNet: 8258,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "3970f155-baea-4d1a-949e-583e12bb8dda",
        state: 2,
        endingTime: "2021-09-22T11:21:48.069Z",
        remainingTimeInSeconds: 511096,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 227,
        currentHighestBidValueNet: 227,
        minimumRequiredAsk: 10264,
        minimumRequiredAskNet: 10264,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "b0580029-b9aa-4d6e-b08b-68279a79ff34",
        state: 2,
        endingTime: "2021-09-23T08:00:00.000Z",
        remainingTimeInSeconds: 585388,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 61,
        currentHighestBidValueNet: 72.59,
        minimumRequiredAsk: 6083,
        minimumRequiredAskNet: 7238.77,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
    {
        uuid: "a85524a2-c231-4ecd-9b6d-1218ae832495",
        state: 2,
        endingTime: "2021-09-30T17:06:00.000Z",
        remainingTimeInSeconds: 1222948,
        remainingTimeForInstantPurchaseInSeconds: null,
        instantPurchasePossibleUntil: null,
        _fk_uuid_highestBiddingBuyerUser: null,
        currentHighestBidValue: 1440,
        currentHighestBidValueNet: 1713.6,
        minimumRequiredAsk: 22411,
        minimumRequiredAskNet: 26669.09,
        numBids: 0,
        amIHighestBidder: false,
        biddingAgentValue: null,
        isMinAskReached: false,
        isCrossBorderNetSale: false,
    },
];
